<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETYVNRl\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETYVNRl/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerETYVNRl.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerETYVNRl\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerETYVNRl\appAppKernelProdContainer([
    'container.build_hash' => 'ETYVNRl',
    'container.build_id' => '08c7803d',
    'container.build_time' => 1704822724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETYVNRl');
